### ISSUE TITLE
Toggling Namespaces Shouldn't Break CSS Data Tags

### ISSUE THREAD

**Issue by jacklaing** [Roam-Research/issues#324]
**Problem**

I'm using data-tags to append emojis to the beginning of tags and page links, to help identify page types at a glance. e.g. [[📚Source/Title]]

However, toggling namespaces breaks this, regardless of whether the data tag is linked to the word before or after the slash.

**Proposed Solution**

If we could toggle namespaces and still retain all data-tags, this would be an amazing way to see what namespace a page belongs to with a shorter link. e.g. We would know that [[📚Title]] belongs to the Source namespace.

**Comment by matiassingers** [comment]
The elements retain the data-tags when I toggle the 3 different namespace displays options (C-c C-l), here's how I've been styling them:

```css
span[data-link-title^="People"] .rm-page-ref {
    color: #d9822b;
}

span[data-link-title^="People"] .rm-page-ref:before {
    content: "\01F464";
}

span[data-link-title^="Book"] .rm-page-ref:before {
    content: "\01F4DA";
}
```
